-- Óptica Alba
-- Cuentas por cobrar de ventas realizadas fuera del sistema.
-- Ejecutar después de 49_cierre_automatico_pagos_institucionales.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.cuentas_manuales (
  id_cuenta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario UUID NOT NULL,
  cliente_nombre TEXT NOT NULL,
  cliente_telefono TEXT,
  referencia TEXT,
  fecha_venta DATE NOT NULL,
  montura TEXT NOT NULL,
  precio_venta NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_venta NUMERIC(12,2) NOT NULL,
  monto_cancelado_historico NUMERIC(12,2) NOT NULL DEFAULT 0,
  estado TEXT NOT NULL DEFAULT 'PENDIENTE',
  observaciones TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT cuentas_manuales_precio_check
    CHECK (precio_venta >= 0),
  CONSTRAINT cuentas_manuales_total_check
    CHECK (total_venta > 0),
  CONSTRAINT cuentas_manuales_historico_check
    CHECK (
      monto_cancelado_historico >= 0 AND
      monto_cancelado_historico <= total_venta
    ),
  CONSTRAINT cuentas_manuales_estado_check
    CHECK (estado IN ('PENDIENTE', 'PAGADA'))
);

CREATE TABLE IF NOT EXISTS public.pagos_cuentas_manuales (
  id_pago BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuenta BIGINT NOT NULL
    REFERENCES public.cuentas_manuales(id_cuenta)
    ON DELETE RESTRICT,
  id_caja BIGINT NOT NULL
    REFERENCES public.cajas(id_caja)
    ON DELETE RESTRICT,
  id_usuario UUID NOT NULL,
  monto NUMERIC(12,2) NOT NULL,
  metodo_pago TEXT NOT NULL,
  observaciones TEXT,
  fecha_pago TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pagos_cuentas_manuales_monto_check
    CHECK (monto > 0),
  CONSTRAINT pagos_cuentas_manuales_metodo_check
    CHECK (
      metodo_pago IN ('EFECTIVO', 'YAPE', 'TRANSFERENCIA')
    )
);

ALTER TABLE public.movimientos_caja
  ADD COLUMN IF NOT EXISTS id_cuenta_manual BIGINT;

DO $do$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'movimientos_caja_cuenta_manual_fkey'
      AND conrelid = 'public.movimientos_caja'::regclass
  ) THEN
    ALTER TABLE public.movimientos_caja
      ADD CONSTRAINT movimientos_caja_cuenta_manual_fkey
      FOREIGN KEY (id_cuenta_manual)
      REFERENCES public.cuentas_manuales(id_cuenta)
      ON DELETE RESTRICT;
  END IF;
END;
$do$;

CREATE INDEX IF NOT EXISTS idx_cuentas_manuales_cliente
  ON public.cuentas_manuales (cliente_nombre);

CREATE INDEX IF NOT EXISTS idx_cuentas_manuales_estado
  ON public.cuentas_manuales (estado, fecha_venta DESC);

CREATE INDEX IF NOT EXISTS idx_pagos_cuentas_manuales_cuenta
  ON public.pagos_cuentas_manuales (id_cuenta, fecha_pago DESC);

CREATE INDEX IF NOT EXISTS idx_pagos_cuentas_manuales_caja
  ON public.pagos_cuentas_manuales (id_caja, fecha_pago DESC);

CREATE INDEX IF NOT EXISTS idx_movimientos_caja_cuenta_manual
  ON public.movimientos_caja (id_cuenta_manual)
  WHERE id_cuenta_manual IS NOT NULL;

ALTER TABLE public.cuentas_manuales
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.pagos_cuentas_manuales
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.cuentas_manuales
  FROM anon, authenticated;

REVOKE ALL ON TABLE public.pagos_cuentas_manuales
  FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.registrar_cuenta_manual(
  p_cliente_nombre TEXT,
  p_cliente_telefono TEXT,
  p_referencia TEXT,
  p_fecha_venta DATE,
  p_montura TEXT,
  p_precio_venta NUMERIC,
  p_total_venta NUMERIC,
  p_monto_cancelado_historico NUMERIC,
  p_pago_hoy NUMERIC,
  p_metodo_pago_hoy TEXT,
  p_observaciones TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_id_cuenta BIGINT;
  v_id_caja BIGINT;
  v_id_pago BIGINT;
  v_cliente TEXT;
  v_telefono TEXT;
  v_referencia TEXT;
  v_montura TEXT;
  v_observaciones TEXT;
  v_precio NUMERIC(12,2);
  v_total NUMERIC(12,2);
  v_historico NUMERIC(12,2);
  v_pago_hoy NUMERIC(12,2);
  v_metodo TEXT;
  v_estado TEXT;
  v_concepto TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.';
  END IF;

  IF NOT public.fn_caja_usuario_activo() THEN
    RAISE EXCEPTION
      'El usuario autenticado no tiene un perfil activo.';
  END IF;

  IF public.fn_caja_rol_actual() NOT IN ('ADMINISTRADOR', 'VENDEDOR') THEN
    RAISE EXCEPTION
      'El usuario no tiene permiso para gestionar cuentas manuales.';
  END IF;

  v_cliente := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_cliente_nombre, '')), '\s+', ' ', 'g'),
    ''
  );

  v_montura := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_montura, '')), '\s+', ' ', 'g'),
    ''
  );

  v_telefono := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_cliente_telefono, '')), '\s+', ' ', 'g'),
    ''
  );

  v_referencia := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_referencia, '')), '\s+', ' ', 'g'),
    ''
  );

  v_observaciones := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_observaciones, '')), '\s+', ' ', 'g'),
    ''
  );

  IF v_cliente IS NULL OR LENGTH(v_cliente) < 3 THEN
    RAISE EXCEPTION 'Ingresa el nombre completo del cliente.';
  END IF;

  IF v_montura IS NULL OR LENGTH(v_montura) < 2 THEN
    RAISE EXCEPTION 'Describe la montura vendida.';
  END IF;

  IF p_fecha_venta IS NULL THEN
    RAISE EXCEPTION 'Selecciona la fecha de la venta manual.';
  END IF;

  v_precio := ROUND(COALESCE(p_precio_venta, 0), 2);
  v_total := ROUND(COALESCE(p_total_venta, 0), 2);
  v_historico := ROUND(
    COALESCE(p_monto_cancelado_historico, 0),
    2
  );
  v_pago_hoy := ROUND(COALESCE(p_pago_hoy, 0), 2);

  IF v_precio < 0 THEN
    RAISE EXCEPTION
      'El precio de venta de la montura no es válido.';
  END IF;

  IF v_total <= 0 THEN
    RAISE EXCEPTION
      'El total de la venta debe ser mayor que cero.';
  END IF;

  IF v_historico < 0 OR v_pago_hoy < 0 THEN
    RAISE EXCEPTION
      'Los montos cancelados no pueden ser negativos.';
  END IF;

  IF v_historico + v_pago_hoy > v_total THEN
    RAISE EXCEPTION
      'Los pagos registrados superan el total de la cuenta.';
  END IF;

  IF v_pago_hoy > 0 THEN
    v_metodo := UPPER(TRIM(COALESCE(p_metodo_pago_hoy, '')));

    IF v_metodo NOT IN ('EFECTIVO', 'YAPE', 'TRANSFERENCIA') THEN
      RAISE EXCEPTION 'El medio del pago recibido hoy no es válido.';
    END IF;

    SELECT c.id_caja
    INTO v_id_caja
    FROM public.cajas c
    WHERE c.estado = 'ABIERTA'
    ORDER BY c.fecha_apertura DESC, c.id_caja DESC
    LIMIT 1
    FOR UPDATE;

    IF v_id_caja IS NULL THEN
      RAISE EXCEPTION 'No existe una caja general abierta.';
    END IF;
  END IF;

  v_estado := CASE
    WHEN v_historico + v_pago_hoy >= v_total
    THEN 'PAGADA'
    ELSE 'PENDIENTE'
  END;

  INSERT INTO public.cuentas_manuales (
    id_usuario,
    cliente_nombre,
    cliente_telefono,
    referencia,
    fecha_venta,
    montura,
    precio_venta,
    total_venta,
    monto_cancelado_historico,
    estado,
    observaciones
  )
  VALUES (
    auth.uid(),
    v_cliente,
    v_telefono,
    v_referencia,
    p_fecha_venta,
    v_montura,
    v_precio,
    v_total,
    v_historico,
    v_estado,
    v_observaciones
  )
  RETURNING id_cuenta
  INTO v_id_cuenta;

  IF v_pago_hoy > 0 THEN
    INSERT INTO public.pagos_cuentas_manuales (
      id_cuenta,
      id_caja,
      id_usuario,
      monto,
      metodo_pago,
      observaciones
    )
    VALUES (
      v_id_cuenta,
      v_id_caja,
      auth.uid(),
      v_pago_hoy,
      v_metodo,
      'Pago recibido al registrar la cuenta manual'
    )
    RETURNING id_pago
    INTO v_id_pago;

    v_concepto := CONCAT(
      'Cuenta manual #',
      v_id_cuenta,
      ' · ',
      v_cliente,
      ' · ',
      v_montura,
      CASE
        WHEN v_referencia IS NOT NULL
        THEN ' · ' || v_referencia
        ELSE ''
      END
    );

    INSERT INTO public.movimientos_caja (
      id_caja,
      id_usuario,
      id_venta,
      tipo_movimiento,
      concepto,
      monto,
      fecha_movimiento,
      metodo_pago,
      es_pago_externo,
      id_cuenta_manual
    )
    VALUES (
      v_id_caja,
      auth.uid(),
      NULL,
      'INGRESO',
      v_concepto,
      v_pago_hoy,
      NOW(),
      v_metodo,
      TRUE,
      v_id_cuenta
    );
  END IF;

  RETURN JSONB_BUILD_OBJECT(
    'ok', TRUE,
    'id_cuenta', v_id_cuenta,
    'id_pago', v_id_pago,
    'estado', v_estado,
    'total_venta', v_total,
    'monto_cancelado', v_historico + v_pago_hoy,
    'saldo_pendiente', v_total - v_historico - v_pago_hoy
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.registrar_pago_cuenta_manual(
  p_id_cuenta BIGINT,
  p_monto NUMERIC,
  p_metodo_pago TEXT,
  p_observaciones TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_cuenta public.cuentas_manuales%ROWTYPE;
  v_id_caja BIGINT;
  v_id_pago BIGINT;
  v_pagado_sistema NUMERIC(12,2) := 0;
  v_cancelado NUMERIC(12,2) := 0;
  v_saldo NUMERIC(12,2) := 0;
  v_monto NUMERIC(12,2);
  v_metodo TEXT;
  v_observaciones TEXT;
  v_estado TEXT;
  v_concepto TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.';
  END IF;

  IF NOT public.fn_caja_usuario_activo() THEN
    RAISE EXCEPTION
      'El usuario autenticado no tiene un perfil activo.';
  END IF;

  IF public.fn_caja_rol_actual() NOT IN ('ADMINISTRADOR', 'VENDEDOR') THEN
    RAISE EXCEPTION
      'El usuario no tiene permiso para cobrar cuentas manuales.';
  END IF;

  SELECT cm.*
  INTO v_cuenta
  FROM public.cuentas_manuales cm
  WHERE cm.id_cuenta = p_id_cuenta
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No se encontró la cuenta manual.';
  END IF;

  SELECT COALESCE(SUM(pcm.monto), 0)
  INTO v_pagado_sistema
  FROM public.pagos_cuentas_manuales pcm
  WHERE pcm.id_cuenta = v_cuenta.id_cuenta;

  v_cancelado := ROUND(
    v_cuenta.monto_cancelado_historico + v_pagado_sistema,
    2
  );

  v_saldo := ROUND(
    GREATEST(v_cuenta.total_venta - v_cancelado, 0),
    2
  );

  IF v_saldo <= 0 THEN
    RAISE EXCEPTION 'La cuenta ya está pagada.';
  END IF;

  v_monto := ROUND(COALESCE(p_monto, 0), 2);

  IF v_monto <= 0 THEN
    RAISE EXCEPTION 'El monto debe ser mayor que cero.';
  END IF;

  IF v_monto > v_saldo THEN
    RAISE EXCEPTION
      'El pago supera el saldo pendiente de S/ %.',
      TO_CHAR(v_saldo, 'FM999999990.00');
  END IF;

  v_metodo := UPPER(TRIM(COALESCE(p_metodo_pago, '')));

  IF v_metodo NOT IN ('EFECTIVO', 'YAPE', 'TRANSFERENCIA') THEN
    RAISE EXCEPTION 'El medio de pago no es válido.';
  END IF;

  v_observaciones := NULLIF(
    REGEXP_REPLACE(TRIM(COALESCE(p_observaciones, '')), '\s+', ' ', 'g'),
    ''
  );

  SELECT c.id_caja
  INTO v_id_caja
  FROM public.cajas c
  WHERE c.estado = 'ABIERTA'
  ORDER BY c.fecha_apertura DESC, c.id_caja DESC
  LIMIT 1
  FOR UPDATE;

  IF v_id_caja IS NULL THEN
    RAISE EXCEPTION 'No existe una caja general abierta.';
  END IF;

  INSERT INTO public.pagos_cuentas_manuales (
    id_cuenta,
    id_caja,
    id_usuario,
    monto,
    metodo_pago,
    observaciones
  )
  VALUES (
    v_cuenta.id_cuenta,
    v_id_caja,
    auth.uid(),
    v_monto,
    v_metodo,
    v_observaciones
  )
  RETURNING id_pago
  INTO v_id_pago;

  v_concepto := CONCAT(
    'Cuenta manual #',
    v_cuenta.id_cuenta,
    ' · ',
    v_cuenta.cliente_nombre,
    ' · ',
    v_cuenta.montura,
    CASE
      WHEN v_cuenta.referencia IS NOT NULL
      THEN ' · ' || v_cuenta.referencia
      ELSE ''
    END
  );

  INSERT INTO public.movimientos_caja (
    id_caja,
    id_usuario,
    id_venta,
    tipo_movimiento,
    concepto,
    monto,
    fecha_movimiento,
    metodo_pago,
    es_pago_externo,
    id_cuenta_manual
  )
  VALUES (
    v_id_caja,
    auth.uid(),
    NULL,
    'INGRESO',
    v_concepto,
    v_monto,
    NOW(),
    v_metodo,
    TRUE,
    v_cuenta.id_cuenta
  );

  v_cancelado := ROUND(v_cancelado + v_monto, 2);
  v_saldo := ROUND(
    GREATEST(v_cuenta.total_venta - v_cancelado, 0),
    2
  );

  v_estado := CASE
    WHEN v_saldo <= 0 THEN 'PAGADA'
    ELSE 'PENDIENTE'
  END;

  UPDATE public.cuentas_manuales
  SET
    estado = v_estado,
    actualizado_en = NOW()
  WHERE id_cuenta = v_cuenta.id_cuenta;

  RETURN JSONB_BUILD_OBJECT(
    'ok', TRUE,
    'id_cuenta', v_cuenta.id_cuenta,
    'id_pago', v_id_pago,
    'id_caja', v_id_caja,
    'monto', v_monto,
    'metodo_pago', v_metodo,
    'monto_cancelado', v_cancelado,
    'saldo_pendiente', v_saldo,
    'estado', v_estado
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.listar_cuentas_manuales()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.';
  END IF;

  IF NOT public.fn_caja_usuario_activo() THEN
    RAISE EXCEPTION
      'El usuario autenticado no tiene un perfil activo.';
  END IF;

  IF public.fn_caja_rol_actual() NOT IN ('ADMINISTRADOR', 'VENDEDOR') THEN
    RAISE EXCEPTION
      'El usuario no tiene permiso para consultar cuentas manuales.';
  END IF;

  RETURN COALESCE(
    (
      SELECT JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'id_cuenta', cm.id_cuenta,
          'id_usuario', cm.id_usuario,
          'usuario', COALESCE(
            NULLIF(TRIM(CONCAT_WS(' ', u.nombres, u.apellidos)), ''),
            'Usuario'
          ),
          'cliente_nombre', cm.cliente_nombre,
          'cliente_telefono', COALESCE(cm.cliente_telefono, ''),
          'referencia', COALESCE(cm.referencia, ''),
          'fecha_venta', cm.fecha_venta,
          'montura', cm.montura,
          'precio_venta', cm.precio_venta,
          'total_venta', cm.total_venta,
          'monto_cancelado_historico',
            cm.monto_cancelado_historico,
          'cobros_sistema', COALESCE(p.cobrado, 0),
          'monto_cancelado', LEAST(
            cm.total_venta,
            cm.monto_cancelado_historico + COALESCE(p.cobrado, 0)
          ),
          'saldo_pendiente', GREATEST(
            cm.total_venta -
              cm.monto_cancelado_historico -
              COALESCE(p.cobrado, 0),
            0
          ),
          'estado', CASE
            WHEN
              cm.total_venta -
              cm.monto_cancelado_historico -
              COALESCE(p.cobrado, 0) <= 0
            THEN 'PAGADA'
            ELSE 'PENDIENTE'
          END,
          'observaciones', COALESCE(cm.observaciones, ''),
          'creado_en', cm.creado_en,
          'actualizado_en', cm.actualizado_en,
          'ultimo_pago_en', p.ultimo_pago
        )
        ORDER BY
          CASE
            WHEN
              cm.total_venta -
              cm.monto_cancelado_historico -
              COALESCE(p.cobrado, 0) > 0
            THEN 0
            ELSE 1
          END,
          cm.fecha_venta DESC,
          cm.id_cuenta DESC
      )
      FROM public.cuentas_manuales cm
      LEFT JOIN public.usuarios u
        ON u.id_usuario = cm.id_usuario
      LEFT JOIN LATERAL (
        SELECT
          COALESCE(SUM(pcm.monto), 0) AS cobrado,
          MAX(pcm.fecha_pago) AS ultimo_pago
        FROM public.pagos_cuentas_manuales pcm
        WHERE pcm.id_cuenta = cm.id_cuenta
      ) p ON TRUE
    ),
    '[]'::JSONB
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.listar_pagos_cuenta_manual(
  p_id_cuenta BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado.';
  END IF;

  IF NOT public.fn_caja_usuario_activo() THEN
    RAISE EXCEPTION
      'El usuario autenticado no tiene un perfil activo.';
  END IF;

  IF public.fn_caja_rol_actual() NOT IN ('ADMINISTRADOR', 'VENDEDOR') THEN
    RAISE EXCEPTION
      'El usuario no tiene permiso para consultar estos pagos.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.cuentas_manuales cm
    WHERE cm.id_cuenta = p_id_cuenta
  ) THEN
    RAISE EXCEPTION 'No se encontró la cuenta manual.';
  END IF;

  RETURN COALESCE(
    (
      SELECT JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'id_pago', pcm.id_pago,
          'id_cuenta', pcm.id_cuenta,
          'id_caja', pcm.id_caja,
          'id_usuario', pcm.id_usuario,
          'usuario', COALESCE(
            NULLIF(TRIM(CONCAT_WS(' ', u.nombres, u.apellidos)), ''),
            'Usuario'
          ),
          'monto', pcm.monto,
          'metodo_pago', pcm.metodo_pago,
          'fecha_pago', pcm.fecha_pago,
          'observaciones', COALESCE(pcm.observaciones, '')
        )
        ORDER BY pcm.fecha_pago DESC, pcm.id_pago DESC
      )
      FROM public.pagos_cuentas_manuales pcm
      LEFT JOIN public.usuarios u
        ON u.id_usuario = pcm.id_usuario
      WHERE pcm.id_cuenta = p_id_cuenta
    ),
    '[]'::JSONB
  );
END;
$function$;

/*
 * Conserva el listado de Caja e identifica los ingresos procedentes de una
 * cuenta manual para mostrar su origen correctamente en el frontend.
 */
CREATE OR REPLACE FUNCTION public.listar_movimientos_caja_actual()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_id_caja BIGINT;
BEGIN
  IF NOT public.fn_caja_usuario_activo() THEN
    RAISE EXCEPTION
      'El usuario autenticado no tiene un perfil activo.';
  END IF;

  SELECT c.id_caja
  INTO v_id_caja
  FROM public.cajas c
  WHERE c.estado = 'ABIERTA'
  ORDER BY c.fecha_apertura DESC, c.id_caja DESC
  LIMIT 1;

  IF v_id_caja IS NULL THEN
    RETURN '[]'::JSONB;
  END IF;

  RETURN COALESCE(
    (
      SELECT JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'id_movimiento', mc.id_movimiento_caja,
          'id_caja', mc.id_caja,
          'id_venta', mc.id_venta,
          'id_cuenta_manual', mc.id_cuenta_manual,
          'tipo', mc.tipo_movimiento,
          'concepto', mc.concepto,
          'monto', mc.monto,
          'fecha', mc.fecha_movimiento,
          'automatico', mc.id_venta IS NOT NULL,
          'pago_externo',
            COALESCE(mc.es_pago_externo, FALSE) OR
            (
              mc.id_venta IS NULL AND
              mc.tipo_movimiento = 'INGRESO'
            ),
          'metodo_pago', CASE
            WHEN mc.tipo_movimiento = 'INGRESO'
            THEN COALESCE(mc.metodo_pago, 'EFECTIVO')
            ELSE NULL
          END
        )
        ORDER BY mc.fecha_movimiento DESC
      )
      FROM public.movimientos_caja mc
      WHERE mc.id_caja = v_id_caja
    ),
    '[]'::JSONB
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.registrar_cuenta_manual(
  TEXT, TEXT, TEXT, DATE, TEXT, NUMERIC, NUMERIC,
  NUMERIC, NUMERIC, TEXT, TEXT
) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.registrar_pago_cuenta_manual(
  BIGINT, NUMERIC, TEXT, TEXT
) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.listar_cuentas_manuales()
  FROM PUBLIC;

REVOKE ALL ON FUNCTION public.listar_pagos_cuenta_manual(BIGINT)
  FROM PUBLIC;

REVOKE ALL ON FUNCTION public.listar_movimientos_caja_actual()
  FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.registrar_cuenta_manual(
  TEXT, TEXT, TEXT, DATE, TEXT, NUMERIC, NUMERIC,
  NUMERIC, NUMERIC, TEXT, TEXT
) TO authenticated;

GRANT EXECUTE ON FUNCTION public.registrar_pago_cuenta_manual(
  BIGINT, NUMERIC, TEXT, TEXT
) TO authenticated;

GRANT EXECUTE ON FUNCTION public.listar_cuentas_manuales()
  TO authenticated;

GRANT EXECUTE ON FUNCTION public.listar_pagos_cuenta_manual(BIGINT)
  TO authenticated;

GRANT EXECUTE ON FUNCTION public.listar_movimientos_caja_actual()
  TO authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
